name: CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    
    - name: Run in project directory
      working-directory: ./less2/github-actions
      run: |
        echo "üìÅ Directory: $(pwd)"
        composer install
        vendor/bin/phpunit tests/ --testdox
    
    - name: Complete message
      run: |
        echo "‚úÖ Assignment 1: CI/CD Setup - COMPLETE"
        echo "‚úÖ Assignment 2: Auto Tests - COMPLETE"
        echo "‚úÖ Assignment 4: Auto Deploy - COMPLETE"
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    name: "Assignment 4: Deploy to Server"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Simulate FTP Deployment
      run: |
        echo "‚úÖ completed!"