name: "CI CD Pipeline"

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ci-and-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    
    - name: Setup project
      working-directory: ./less2/github-actions
      run: |
        echo "üöÄ Assignment 1: Setting up CI/CD..."
        composer install --prefer-dist --no-progress
        composer dump-autoload -o
    
    - name: Setup project
      working-directory: ./less2/github-actions
      run: |
        echo "üöÄ Assignment 1: Setting up CI/CD..."
        composer install --prefer-dist --no-progress
        composer dump-autoload -o
        
        chmod +x vendor/bin/phpunit
    
    - name: Run tests
      working-directory: ./less2/github-actions
      run: |
        echo "üß™ Assignment 2: Running auto tests..."
        php vendor/bin/phpunit tests/ --testdox --colors=always  # –ò—Å–ø–æ–ª—å–∑—É–µ–º php –ø–µ—Ä–µ–¥
    
    - name: Mark assignments complete
      run: |
        echo "‚úÖ ASSIGNMENT 1: CI/CD Setup - COMPLETE"
        echo "‚úÖ ASSIGNMENT 2: Auto Tests - COMPLETE"